root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  pre_cmd = ["swag init -g cmd/api_info.go --parseDependency --parseInternal"]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  
  delay = 1000 
  
  exclude_dir = ["assets", "tmp", "vendor", "docs", "node_modules", ".git", "storage"]
  
  include_ext = ["go"]
  exclude_ext = ["_test.go", "html", "js", "json", "md", "yml", "yaml"]
  
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
